<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_CheckoutThankYouPage
*/
?>
<?php
/**
 * @var $block Amasty\CheckoutThankYouPage\Block\Onepage\Success\Details
 * @var $escaper Magento\Framework\Escaper
 */
?>

<div class="account">
    <div class="column main">
        <div class="block block-order-details">
            <div class="block-title">
                <strong><?= $escaper->escapeHtml(__('Order details:')) ?></strong>
            </div>
            <div class="order-date">
                <?= $escaper->escapeHtml(__('Order Date:')) ?> <?= $escaper->escapeHtml(
                    $block->formatDate(
                        $block->getOrder()->getCreatedAt(),
                        \IntlDateFormatter::LONG
                    )
                ) ?>
                <?= $block->getChildHtml('delivery') ?>
                <span class="delivery-date"><?= $block->escapeHtml($block->getDeliveryInfo()) ?></span>
            </div>
        </div>

        <?= $block->getChildHtml('info') ?>
        <?= $block->getChildHtml('comments') ?>
        <?= $block->getChildHtml('order_view') ?>
    </div>
</div>
