<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_CheckoutThankYouPage
*/
?>
<?php
/**
 * @var $block Magento\Framework\View\Element\Template
 * @var $viewModel Amasty\CheckoutThankYouPage\ViewModel\SuccessPage
 */
 $viewModel = $block->getViewModel() ?>

<?php if ($viewModel->isEnable()): ?>
    <?= $block->getChildHtml('amasty.checkout.success.page') ?>
<?php else: ?>
    <?= $block->getChildHtml('magento.success.page') ?>
<?php endif; ?>
