<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_CheckoutDeliveryDate
*/
?>
<?php
/** @var $block Amasty\CheckoutDeliveryDate\Block\Config\DDLayoutBuilder */
?>

<script type="text/javascript">
    if (!window.amastyCheckoutConfig) {
        window.amastyCheckoutConfig = {};
    }

    window.amastyCheckoutConfig.deliveryDateInstalled = true;
</script>

