<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<section class="page-landing">
    <img class="logo" src="<?= $this->basePath() ?>/pub/images/magento-logo.svg" alt="Magento"/>
    <p class="text-version">
        <?= 'Version' . ' ' . $this->version ?>
    </p>
    <p class="text-welcome">
        Welcome to Codazon theme.
        <br>
        Magento 2.4 disabled installation method by web browser. You should use ssh command line to install theme, move to your root magento folder and run this comand:
        <pre>php bin/magento setup:upgrade</prev>
    </p>
</section>
