<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $selectionId = $block->getSelectionId(); ?>

<script type="text/x-magento-template" id="tier-prices-template-<?php echo (int)$selectionId; ?>">
    <ul class="prices-tier items">
        <% _.each(tierPrices, function(item, key) { %>
        <%  var priceStr = '<span class="price-container price-tier_price">'
                + '<span data-price-amount="' + priceUtils.formatPrice(item.prices.finalPrice.amount, currencyFormat) + '"'
                + ' data-price-type=""' + ' class="price-wrapper ">'
                + '<span class="price">' + priceUtils.formatPrice(item.prices.finalPrice.amount, currencyFormat) + '</span>'
                + '</span>'
            + '</span>'; %>
        <li class="item">
            <%= '<?= $block->escapeHtml(__('Buy %1 for %2 each and', '%1', '%2')) ?>'
            .replace('%1', item.price_qty)
            .replace('%2', priceStr) %>
            <strong class="benefit">
                <?= $block->escapeHtml(__('save')) ?><span
                        class="percent tier-<%= key %>">&nbsp;<%= Math.round(item.percentage_value) %></span>%
            </strong>
        </li>
        <% }); %>
    </ul>
</script>
<div data-role="tier-price-block-<?php echo (int)$selectionId; ?>"></div>
