<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_CheckoutThankYouPage
*/
?>
<?php
/**
 * @var $block Magento\Sales\Block\Order\View
 * @var $escaper Magento\Framework\Escaper
 */

// @codingStandardsIgnoreFile
?>

<div class="order-details-items ordered">
    <?php $order = $block->getOrder() ?>

    <div class="order-title">
        <strong><?= $escaper->escapeHtml(__('Items Ordered')) ?></strong>
        <?php if ($order->getTracksCollection()->count()): ?>
            <?= $block->getChildHtml('tracking-info-link') ?>
        <?php endif; ?>
    </div>

    <?= $block->getChildHtml('order_items') ?>
    <?= $block->getChildHtml('amasty_checkout_gift_wrap') ?>
</div>
