<?php
    /** @var \Magento\Framework\View\Element\Template $block */
    /** @var \Amasty\GoogleAddressAutocomplete\ViewModel\Init $viewModel */

    $viewModel = $block->getData('view_model');
?>

<?php if ($viewModel->isEnabled() && ($apiKey = $viewModel->getApiKey())): ?>
    <script>
        function amAutocompleteGmapsInit() {
            require(['Amasty_GoogleAddressAutocomplete/js/autocomplete'], function (autocomplete) {
                autocomplete.options = <?= /* @noEscape */ $viewModel->getOptionsJson() ?>;
                autocomplete.isReady(true);
            });
        }
    </script>

    <script
        src="https://maps.googleapis.com/maps/api/js?key=<?=
        /* @noEscape */ $block->stripTags($apiKey);?>&libraries=places&callback=amAutocompleteGmapsInit"
        async defer>
    </script>
<?php endif; ?>
