<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_CheckoutCore
*/
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\Options */ ?>

<?php $_options = $block->decorateArray($block->getOptions()) ?>
<?php if (count($_options)): ?>
    <?php foreach ($_options as $_option): ?>
        <?= $block->getOptionHtml($_option) ?>
    <?php endforeach; ?>
<?php endif; ?>
