<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_CheckoutDeliveryDate
*/
?>
<?php
/** @var \Amasty\CheckoutDeliveryDate\Block\Adminhtml\Sales\Order\Create\Deliverydate $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
</section><section class="admin__page-section amasty-deliverydate">
    <div class="admin__page-section-title">
        <span class="title"><?= $escaper->escapeHtml(__('Delivery Information')) ?></span>
    </div>
    <?php foreach ($block->getFormElements() as $element): ?>
        <?= /* @noEscape */ $element->toHtml() ?>
    <?php endforeach; ?>
