<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Select */ ?>
<?php $_option = $block->getOption(); ?>
<?php $_selections = $_option->getSelections(); ?>
<?php $_default = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>
<?php $isEnableImages = $this->helper('Ewave\ExtendedBundleProduct\Helper\Data')->showImages(); ?>
<div class="field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>">
    <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
        <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <div class="bundle-single" data-role="bundle-price-option-<?php echo (int)$_option->getId() ?>-<?php echo (int)$_selections[0]->getSelectionId() ?>">
                <?php if ($isEnableImages): ?>
                    <?php $imageUrl = $this->helper('Magento\Catalog\Helper\Image')->init($_selections[0], 'product_thumbnail_image')->getUrl(); ?>
                    <img data-image="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>" class="img" src="<?php echo $block->escapeUrl($imageUrl); ?>" alt="<?php echo $block->escapeHtml($_selections[0]->getName()) ?>" title="<?php echo $block->escapeHtml($_selections[0]->getName()) ?>">
                    <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selections[0]) ?>
                    <?php if ($tierPriceBlock = $block->getTierPriceRenderer()): ?>
                        <?= /* @noEscape */ $tierPriceBlock->renderTierPrice($_selections[0]) ?>
                    <?php endif; ?>
                    <input type="hidden"
                           class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                           name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           id="bundle-option-<?php echo (int)$_option->getId() ?>-<?php echo (int)$_selections[0]->getSelectionId() ?>"
                           value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"
                           checked="checked" />
                <?php else:?>
                    <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selections[0]) ?>
                    <?php if ($tierPriceBlock = $block->getTierPriceRenderer()): ?>
                        <?= /* @noEscape */ $tierPriceBlock->renderTierPrice($_selections[0]) ?>
                    <?php endif; ?>
                    <input type="hidden"
                           class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                           name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"
                           id="bundle-option-<?php echo (int)$_option->getId() ?>-<?php echo (int)$_selections[0]->getSelectionId() ?>"
                           checked="checked" />
                <?php endif; ?>
            </div>
            <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.select.selection')): ?>
                <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selections[0])->toHtml(); ?>
            <?php endif; ?>
        <?php else:?>
            <?php if ($isEnableImages): ?>
                <?php foreach ($_selections as $_selection): ?>
                    <?php $imageUrl = $this->helper('Magento\Catalog\Helper\Image')->init($_selection, 'product_thumbnail_image')->getUrl(); ?>
                    <span class="bundleimg-wrap" data-role="bundle-price-option-<?php echo (int)$_option->getId() ?>-<?php echo (int)$_selection->getSelectionId() ?>">
                        <img data-image="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>" class="bundle-img" src="<?php echo $block->escapeUrl($imageUrl); ?>" alt="<?php echo $block->escapeHtml($_selection->getName()) ?>" title="<?php echo $block->escapeHtml($_selection->getName()) ?>">
                    </span>
                <?php endforeach; ?>
            <?php endif; ?>
            <div class="bundle-item">
                <select id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                        name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                        data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                        class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?> product bundle option bundle-option-select change-container-classname"
                    <?php if ($_option->getRequired()) echo 'data-validate = {required:true}' ?>>
                    <option value=""><?php /* @escapeNotVerified */ echo __('Choose a selection...') ?></option>
                    <?php foreach ($_selections as $_selection): ?>
                        <option value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                            <?php if ($block->isSelected($_selection)) echo ' selected="selected"' ?>
                            <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>>
                            <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selection, false) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <?php if ($tierPriceBlock = $block->getTierPriceRenderer()): ?>
                    <div id="option-tier-prices-<?= $block->escapeHtml($_option->getId()) ?>" class="option-tier-prices">
                        <?php foreach ($_selections as $_selection) : ?>
                            <div data-role="selection-tier-prices"
                                 data-selection-id="<?= $block->escapeHtml($_selection->getSelectionId()) ?>"
                                 class="selection-tier-prices">
                                <?= /* @noEscape */ $tierPriceBlock->renderTierPrice($_selection) ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
            <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.select.selection')): ?>
                <?php foreach ($_selections as $_selection): ?>
                    <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selection)->toHtml(); ?>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endif; ?>
        <div class="nested">
            <div class="field qty qty-holder">
                <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input">
                    <span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span>
                </label>
                <div class="control">
                    <input <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?>
                           id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input"
                           class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>"
                           type="number"
                           name="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           data-selector="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           value="<?php /* @escapeNotVerified */ echo $_defaultQty ?>"/>
                </div>
            </div>
        </div>
    </div>
</div>
