<?php
/**
 * Copyright © 2017 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
    $widget = [
        "Codazon_ProductFilter/js/firstload" => [
            "ajaxUrl"    => $this->getUrl('themeoptions/ajax/slideshow'),
            "currentUrl" => $this->getUrl(),
            "jsonData"   => $this->getFilterData()
        ]
    ];
?>
<style>
.tripple-bounce-spinner {
  margin: 0px auto 0;
  width: 70px;
  text-align: center;
}

.tripple-bounce-spinner > div {
  width: 18px;
  height: 18px;
  background-color: #333;

  border-radius: 100%;
  display: inline-block;
  -webkit-animation: sk-bouncedelay 1.4s infinite ease-in-out both;
  animation: sk-bouncedelay 1.4s infinite ease-in-out both;
}

.tripple-bounce-spinner .bounce1 {
  -webkit-animation-delay: -0.32s;
  animation-delay: -0.32s;
}

.tripple-bounce-spinner .bounce2 {
  -webkit-animation-delay: -0.16s;
  animation-delay: -0.16s;
}

@-webkit-keyframes sk-bouncedelay {
  0%, 80%, 100% { -webkit-transform: scale(0) }
  40% { -webkit-transform: scale(1.0) }
}

@keyframes sk-bouncedelay {
  0%, 80%, 100% { 
    -webkit-transform: scale(0);
    transform: scale(0);
  } 40% { 
    -webkit-transform: scale(1.0);
    transform: scale(1.0);
  }
}
@media (min-width: 768px){
    .tripple-bounce-spinner {
        padding-top:<?php echo $this->getPadding()-20?>px; padding-bottom:<?php echo $this->getPadding()?>px;
    }
}
@media (max-width: 768px){
    .tripple-bounce-spinner {
        padding-top:50px; padding-bottom:50px;
    }
}
</style>
<div class="no-loaded" data-mage-init='<?= json_encode($widget) ?>' >
    <div class="slideshow tripple-bounce-spinner">
      <div class="bounce1"></div>
      <div class="bounce2"></div>
      <div class="bounce3"></div>
    </div>
</div>
