<?php
/**
 * Copyright © Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $serializedCheckoutConfig = $block->getSerializedCheckoutConfig();
$scriptString = <<<script
    window.checkoutConfig = {$serializedCheckoutConfig};
    // Create aliases for customer.js model from customer module
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.customerData = window.checkoutConfig.customerData;
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php $scriptString = <<<script
    require([
        'mage/url',
        'Magento_Ui/js/block-loader'
    ], function(url, blockLoader) {
        blockLoader("{$block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')))}");
        return url.setBaseUrl('{$block->escapeJs($block->escapeUrl($block->getBaseUrl()))}');
    })
script;
?>
<?= $secureRenderer->renderTag('script', [], $scriptString, false) ?>