<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_CheckoutCore
*/
?>
<?php /** @var \Amasty\CheckoutCore\Block\Adminhtml\System\Config\Expander $block **/ ?>
<script type="text/javascript">
    //<![CDATA[
    require(['Amasty_CheckoutCore/js/fieldset-expander'], function (expander) {
        expander.init('<?=$block->escapeHtml($block->getSection())?>','<?=$block->escapeHtml($block->getExpand())?>');
    });
    //]]>
</script>