<?php
/**
 * Copyright © 2017 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/**
 * Product list template
 *
 * @var $block Codazon\Shopbybrandpro\Block\Brand\BrandInformation
 */ ?>

<?php
$_brand = $this->getBrandOfCurrentProduct();
$block->setBrand($_brand);
$_brandUrl = $_brand->getUrl();
?>
<?php if ($_brand->getOptionId()) : ?>
<?php $label = $_brand->getData('brand_label'); ?>
<div class="product attribute sku brand extra-attr">
    <strong class="type"><?= __('Brand') ?></strong>
    <div class="value"><a href="<?= $_brandUrl ?>"><?= $label ?></a></div>
</div>
<?php endif ?>