<?php
/**
* Copyright © 2020 Codazon. All rights reserved.
* See COPYING.txt for license details.
*/
?>
<?php
$ampHelper = $this->helper(\Codazon\GoogleAmpManager\Helper\Data::class);
$layout = $this->getLayout();
?>
<!doctype html>
<html <?= $this->getData('html_attributes') ?> ⚡>
<head <?= $this->getData('head_attributes') ?>>
    <link rel="icon" type="image/x-icon" href="<?php echo $this->getData('favicon') ?>">
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->getData('favicon') ?>">
    <?= $this->getTitle() ?>
    <?= $this->getMetaData() ?>
    <meta name="amp-experiments-opt-in" content="amp-next-page">
    <link  rel="canonical" href="<?php echo $ampHelper->getCanonicalUrl() ?>" />
    <?= $this->getHeadAdditional() ?>
</head>
<body <?= $this->getBodyAttributes() ?>>
    <?= $this->getLayoutContent() ?>
</body>
</html>