<?php
/**
 * Copyright © Dotsquares. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
/** @var \Dotsquares\OrderComment\Block\Order\Comment $block */
?>
<?php if ($block->isShowCommentInAccount()): ?>
    <?php if ($comment = $block->getOrderComment()): ?>
    <div class="block block-order-comment ds-ordercomment-block">
        <div class="block-content">  
            <div class="block-title">
                <strong><?= $block->escapeHtml(__('Order Comment')) ?></strong>
            </div>
            <div class="box-content">
                <?= $block->getOrderCommentHtml(); ?>
            </div>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>
