<?php
/**
 * @var $helper \Dotsquares\Opc\Helper\Data
 */

$helper = $this->helper("Dotsquares\Opc\Helper\Data");
if ($helper && $helper->isCheckoutPage()) : ?>
    <script>
        require.config({
            map: {
                '*': {
                    'Magento_Checkout/js/model/quote': 'Dotsquares_Opc/js/model/quote',
                    'Magento_Checkout/js/checkout-data': 'Dotsquares_Opc/js/checkout-data',
                    'Magento_Checkout/js/model/checkout-data-resolver': 'Dotsquares_Opc/js/model/checkout-data-resolver',
                    'Magento_Checkout/js/view/summary/abstract-total': 'Dotsquares_Opc/js/view/summary/abstract-total',

                    'Magento_Checkout/js/model/shipping-rate-service': 'Dotsquares_Opc/js/model/shipping-rate-service',
                    'Magento_Checkout/js/model/shipping-save-processor/default': 'Dotsquares_Opc/js/model/shipping-save-processor/default',
                    'Magento_Checkout/js/model/shipping-rates-validator': 'Dotsquares_Opc/js/model/shipping-rates-validator',
                    'Magento_Checkout/js/model/new-customer-address': 'Dotsquares_Opc/js/model/new-customer-address',

                    'Magento_Checkout/js/model/payment-service': 'Dotsquares_Opc/js/model/payment-service',

                    'Magento_CheckoutAgreements/js/model/agreement-validator': 'Dotsquares_Opc/js/model/agreement-validator',
                    'Magento_CheckoutAgreements/js/model/agreements-assigner': 'Dotsquares_Opc/js/model/agreements-assigner',

                    'Magento_Paypal/js/action/set-payment-method': 'Dotsquares_Opc/js/action/paypal/set-payment-method',

                    'Magento_Customer/js/action/login': 'Dotsquares_Opc/js/action/login',
                    // to fix infinity loader of payment method block on OPC
                    'Magento_NegotiableQuote/js/view/shipping-address/address-renderer/default': 'Dotsquares_Opc/js/view/shipping-address/address-renderer/default'
                }
            },
            paths: {
                'microplugin': 'Dotsquares_Opc/js/libs/microplugin',
                'sifter': 'Dotsquares_Opc/js/libs/sifter',
                'dotsquaresOpcSelectize': 'Dotsquares_Opc/js/libs/selectize',
                'dotsquaresOpcHelper': 'Dotsquares_Opc/js/helper'
            },
            shim: {
                'dotsquaresOpcSelectize': {
                    'deps': ['jquery', 'microplugin', 'sifter']
                }
            },
            config: {
                mixins: {
                    'Magento_Checkout/js/action/place-order': {
                        'Dotsquares_Opc/js/model/place-order-mixin': true
                    },
                    'Magento_Checkout/js/action/set-payment-information': {
                        'Dotsquares_Opc/js/model/set-payment-information-mixin': true
                    }
                }
            }
        });
    </script>
<?php elseif ($helper->isEnable()) : ?>
    <script>
        require.config({
            map: {
                '*': {
                    'Magento_Checkout/js/model/quote': 'Dotsquares_Opc/js/model/quote',
                    'Magento_Checkout/js/checkout-data': 'Dotsquares_Opc/js/checkout-data',
                    'Magento_Checkout/js/model/payment-service': 'Dotsquares_Opc/js/model/payment-service'
                }
            },
            paths: {
                'microplugin': 'Dotsquares_Opc/js/libs/microplugin',
                'sifter': 'Dotsquares_Opc/js/libs/sifter',
                'dotsquaresOpcSelectize': 'Dotsquares_Opc/js/libs/selectize',
                'dotsquaresOpcHelper': 'Dotsquares_Opc/js/helper'
            },
            config: {
                mixins: {
                    'Magento_Checkout/js/action/place-order': {
                        'Dotsquares_Opc/js/model/place-order-mixin': true
                    }
                }
            }
        });
    </script>
    <?php echo $block->getChildHtml('checkout.gift_options', false) ?>
<?php endif; ?>